spring:
   jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        default-property-inclusion: non_null
        serialization:
         write-dates-as-timestamps: false


